version: '3.8'

services:
  app:
    image: neom_backend:1.0
    deploy:
      replicas: 3
    command: python app.py
    volumes:
      - ./.env:/app/.env

  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  loadbalancer:
    image: dockercloud/haproxy:latest
    ports:
      - "8080:80"
    depends_on:
      - nginx
    deploy:
      mode: global
